server:
  port: 3000

db:
  host: 'lupodev.cbhfq6rfyu8g.ap-northeast-2.rds.amazonaws.com'
  username: 'postgres'
  password: 'lupo1234'
  synchronize: true
  type: 'postgres'

jwt:
  expiresIn: 21600

aws:
  s3AccessKey: 'AKIA2HFWRLLMSH42UJUH'
  s3SecretKey: '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'
  s3Region: 'ap-northeast-2'
  s3Bucket: 'lupo-backend'