db:
  host: 'lupodev.cbhfq6rfyu8g.ap-northeast-2.rds.amazonaws.com'
  username: 'postgres'
  password: 'lupo1234'
  synchronize: true
  type: 'postgres'

jwt:
  secret: 'jiwon0818'

aws:
  s3AccessKey: 'AKIA2HFWRLLMSH42UJUH'
  s3SecretKey: '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'
  s3Region: 'ap-northeast-2'
  s3Bucket: 'lupo-image'