db:
  host: 'lupodev.cbhfq6rfyu8g.ap-northeast-2.rds.amazonaws.com'
  username: 'postgres'
  password: 'lupo1234'
  synchronize: true
  type: 'postgres'

jwt:
  secret: 'jiwon0818'

aws:
  s3Region: 'ap-northeast-2'
  s3Bucket: 'lupo-image'